on: push

jobs:
  build-the-car:
    runs-on: ubuntu-latest
    steps:
      - name: Build the car
        run: |
          mkdir build
          cd build
          touch car.txt
          echo "chassis" >> car.txt
          echo "engine" >> car.txt
          echo "wheels" >> car.txt
